refactor(indexer): use historical storage as checkpoint source (#10789)
# Description of change

This PR extends the `iota-indexer` to support checkpoint ingestion from
S3-compatible historical and live storages as an alternative to a
fullnode gRPC endpoint. Since fullnodes can prune their internal
databases, syncing the indexer from genesis via a fullnode gRPC URL may
result in errors when historical checkpoints are no longer available.

To address this, we extended the `--remote-store-url` argument to accept
either a fullnode gRPC URL or an S3-compatible historical checkpoint
store URL. When provided, the indexer automatically determines the
source type by first attempting a gRPC health check, then falling back
to checking for a MANIFEST file on the object store. If neither probe
succeeds after retrying with exponential backoff, the indexer returns an
error and exits.

For minimal latency at the network tip when using historical storage,
the user can optionally provide `--current-epoch-store-url`, which
points to a live object store serving individual checkpoint files for
the current epoch only.

## Links to any relevant issues

fixes #10723 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration
tests)
- [x] Patch-specific tests (correctness, functionality coverage)

- Ran the indexer to make sure that it actually was syncing from
historical and live storage, used testnet data.
```shell
cargo r -- --database-url postgres://postgres:postgrespw@localhost:5432/iota_indexer  indexer --remote-store-url=https://checkpoints.testnet.iota.cafe/ingestion/historical  --current-epoch-store-url=https://checkpoints.testnet.iota.cafe/ingestion/live --reset-db
```

- Verified that `--current-epoch-store-url` requires
`--remote-store-url` and cannot be used standalone
```shell
cargo r -- --database-url postgres://postgres:postgrespw@localhost:5432/iota_indexer  indexer --current-epoch-store-url=https://checkpoints.testnet.iota.cafe/ingestion/live  --reset-db

error: the following required arguments were not provided:
  --remote-store-url <REMOTE_STORE_URL>
```

### Infrastructure QA (only required for crates that are maintained by
@iotaledger/infrastructure)

- [x] Synchronization of the indexer from genesis for a network
including migration objects.
- [x] Restart of indexer synchronization locally without resetting the
database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### Release Notes

- [x] Indexer: Add the ability to sync checkpoints form historical &
live storages as an alternative checkpoint source to fullnode.