refactor(move-package-alt): Use substring operation instead of lazy regex (#8800)
# Description of change

Minor refactor for `move-package-alt`, where lazy regex operations were
removed in favor of string based ones.

Good to know:
The new package cannot be tested using
```
external-crates/move $ cargo test -p move-package-alt 
```
because it will fail on incorrectly identified doctests.

```
---- crates/move-package-alt/src/dependency/git.rs - dependency::git (line 10) stdout ----
error: expected item, found `.`
 --> crates/move-package-alt/src/dependency/git.rs:11:1
  |
1 | .move/
  | ^ expected item
  |
  = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>

error: aborting due to 1 previous error
```

This, we do not attempt to fix.
The functional way of running the test is:
```
external-crates/move $ cargo nextest run -p move-package-alt
```

If you wonder why the main Cargo.lock file was modified it is because of
nextest. Not sure why does it change that, why it doesn't fail the same
way as the normal `cargo test` though.

## Links to any relevant issues

fixes #8329